<?php

/*
* Template Name: Contact
*/

get_header();
while(have_posts()) : the_post();
?>

<section id="contact__intro" class="intro"><div class="container"><div class="contents"><div class="inner-contents"><h1>Vous désirez <span>nous joindre</span> ?</h1><rwp-wrap><p>Contactez-nous dès maintenant pour découvrir nos forfaits, poser vos questions ou échanger avec un de nos représentants pour débuter une analyse de vos besoins.</p></rwp-wrap></div></div></div></section><section id="contact__form"><div class="container"><div class="contents"><div class="inner-contents"><h2>Contactez-nous</h2><rwp-wrap><p>Remplissez notre formulaire et nous serons ravis de répondre à vos questions et de discuter de vos besoins.</p><ul><li><span>Questions :</span><a href="mailto:info@siterapide.ca">info@siterapide.ca</a></li><li><span>Support :</span><a href="mailto:support@siterapide.ca">support@siterapide.ca</a></li><li><span>Carrière :</span><a href="mailto:cv@siterapide.ca">cv@siterapide.ca</a></li></ul></rwp-wrap></div></div><form method="POST" action="rwpforms"><div class="fields"><div class="field split text"><div class="the-field"><input id="firstname" placeholder="Prénom*" autocomplete="given-name" minlength="3" maxlength="30" required="" type="text" name="firstname"></div></div><div class="field split text"><div class="the-field"><input id="lastname" placeholder="Nom de famille*" autocomplete="family-name" minlength="3" maxlength="30" required="" type="text" name="lastname"></div></div><div class="field split email"><div class="the-field"><input id="email" placeholder="Courriel*" autocomplete="email" required="" type="email" name="email"></div></div><div class="field split tel"><div class="the-field"><input id="phone" placeholder="Téléphone*" autocomplete="tel" minlength="14" maxlength="14" required="" type="tel" name="phone"></div></div><div class="field text"><div class="the-field"><input id="company" placeholder="Nom de l'entreprise" minlength="1" maxlength="50" type="text" name="company"></div></div><div class="field textarea"><div class="the-field"><textarea id="message" name="message" required="" placeholder="Message*"></textarea></div></div></div><div class="buttons"><button class="btn blue has-arrow" type="submit"><span>Envoyer</span><div class="btn-after"><div class="arrow"><svg xmlns="http://www.w3.org/2000/svg" width="35.275" height="23.504" viewBox="0 0 35.275 23.504"><path d="M23.274,0l-.837.82L33.008,11.173H0v1.159H33.008L22.437,22.684l.837.82L34.438,12.572l.837-.82-.837-.82Z" transform="translate(0 0)" fill="#214cf3"></path></svg></div></div></button></div></form></div></section>

<?php endwhile; get_footer(); ?>