<?php

namespace Siterapide\Forms;

class Render{
    
    function __construct(){


    	/*
    	* Display Theme settings tag
    	*/
    	add_action('admin_bar_menu', [$this, 'theme_settings_tab'], 96);

		
		/*
		* Display ACF Admin Elements
		*/
		add_action('init', [$this, 'acf'], 4);
        
    }
    
	
	public function acf(){

		register_post_type('form', array(
	        'labels' => array(
	            'name' => CL === 'fr' ? 'Formulaires' : 'Forms',
	            'singular_name' => CL === 'fr' ? 'Formulaire' : 'Form',
	            'menu_name' => CL === 'fr' ? 'Formulaires' : 'Forms',
	            'all_items' => 'All Forms',
	            'edit_item' => 'Edit Form',
	            'view_item' => 'View Form',
	            'view_items' => 'View Forms',
	            'add_new_item' => 'Add New Form',
	            'add_new' => 'Add New Form',
	            'new_item' => 'New Form',
	            'parent_item_colon' => 'Parent Form:',
	            'search_items' => 'Search Forms',
	            'not_found' => 'No forms found',
	            'not_found_in_trash' => 'No forms found in Trash',
	            'archives' => 'Form Archives',
	            'attributes' => 'Form Attributes',
	            'insert_into_item' => 'Insert into form',
	            'uploaded_to_this_item' => 'Uploaded to this form',
	            'filter_items_list' => 'Filter forms list',
	            'filter_by_date' => 'Filter forms by date',
	            'items_list_navigation' => 'Forms list navigation',
	            'items_list' => 'Forms list',
	            'item_published' => 'Form published.',
	            'item_published_privately' => 'Form published privately.',
	            'item_reverted_to_draft' => 'Form reverted to draft.',
	            'item_scheduled' => 'Form scheduled.',
	            'item_updated' => 'Form updated.',
	            'item_link' => 'Form Link',
	            'item_link_description' => 'A link to a form.',
	        ),
	        'public' => false,
	        'exclude_from_search' => false,
	        'publicly_queryable' => true,
	        'show_ui' => true,
	        'show_in_nav_menus' => true,
	        'show_in_rest' => false,
	        'menu_icon' => 'dashicons-admin-post',
	        'supports' => array(
	            0 => 'title',
	        ),
	        'rewrite' => false,
	        'delete_with_user' => false,
	    ));

	    acf_add_local_field_group( array(
			'key' => 'group_676098ea7d81a',
			'title' => 'Form view',
			'fields' => array(
				array(
					'key' => 'field_676098eab7475',
					'label' => 'Fields',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_67609912b7476',
					'label' => 'Fields',
					'name' => 'fields',
					'aria-label' => '',
					'type' => 'flexible_content',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layouts' => array(
						'layout_6760991a7b566' => array(
							'key' => 'layout_6760991a7b566',
							'name' => 'input',
							'label' => 'Input',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_6760bdcb4506e',
									'label' => 'Label',
									'name' => 'label',
									'aria-label' => '',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'table',
									'sub_fields' => array(
										array(
											'key' => 'field_67641be0c483f',
											'label' => 'Français',
											'name' => 'fr',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_67641be7c4840',
											'label' => 'Anglais',
											'name' => 'en',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_676422464e605',
											'label' => 'Don\'t link',
											'name' => 'do_not_link',
											'aria-label' => '',
											'type' => 'true_false',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'message' => '',
											'default_value' => 0,
											'allow_in_bindings' => 0,
											'ui_on_text' => '',
											'ui_off_text' => '',
											'ui' => 1,
										),
									),
								),
								array(
									'key' => 'field_6760bde24506f',
									'label' => '',
									'name' => '',
									'aria-label' => '',
									'type' => 'message',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'new_lines' => '',
									'esc_html' => 0,
								),
								array(
									'key' => 'field_67609942b7477',
									'label' => 'Type',
									'name' => 'type',
									'aria-label' => '',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'checkbox' => 'checkbox',
										'color' => 'color',
										'date' => 'date',
										'datetime-local' => 'datetime-local',
										'email' => 'email',
										'file' => 'file',
										'hidden' => 'hidden',
										'month' => 'month',
										'number' => 'number',
										'password' => 'password',
										'radio' => 'radio',
										'range' => 'range',
										'tel' => 'tel',
										'text' => 'text',
										'time' => 'time',
										'url' => 'url',
										'week' => 'week',
									),
									'default_value' => false,
									'return_format' => 'value',
									'multiple' => 0,
									'allow_null' => 0,
									'allow_in_bindings' => 0,
									'ui' => 0,
									'ajax' => 0,
									'placeholder' => '',
								),
								array(
									'key' => 'field_67609a5ab7478',
									'label' => 'id',
									'name' => 'id',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_67609a6bb7479',
									'label' => 'name',
									'name' => 'name',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6760ae2c379f1',
									'label' => 'value',
									'name' => 'value',
									'aria-label' => '',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '!=',
												'value' => 'checkbox',
											),
											array(
												'field' => 'field_67609942b7477',
												'operator' => '!=',
												'value' => 'radio',
											),
											array(
												'field' => 'field_67609942b7477',
												'operator' => '!=',
												'value' => 'file',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'table',
									'sub_fields' => array(
										array(
											'key' => 'field_6760c0a543453',
											'label' => 'Français',
											'name' => 'fr',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_6760c0ac43454',
											'label' => 'Anglais',
											'name' => 'en',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_6760c0cb43455',
											'label' => 'No lang',
											'name' => 'nolang',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
									),
								),
								array(
									'key' => 'field_6760aee8379f2',
									'label' => 'min',
									'name' => 'min',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'date',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'datetime-local',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'month',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'number',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'range',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'time',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'week',
											),
										),
									),
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6760af0f379f4',
									'label' => 'max',
									'name' => 'max',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'date',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'datetime-local',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'month',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'number',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'range',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'time',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'week',
											),
										),
									),
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6760b001379f7',
									'label' => 'minlength',
									'name' => 'minlength',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'password',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'tel',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'text',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'url',
											),
										),
									),
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6760b023379f9',
									'label' => 'maxlength',
									'name' => 'maxlength',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'password',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'tel',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'text',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'url',
											),
										),
									),
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6760b3ea379fc',
									'label' => 'pattern',
									'name' => 'pattern',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'email',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'password',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'tel',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'text',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'url',
											),
										),
									),
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6760b27b379fb',
									'label' => 'placeholder',
									'name' => 'placeholder',
									'aria-label' => '',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'email',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'number',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'password',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'tel',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'text',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'url',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'file',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'table',
									'sub_fields' => array(
										array(
											'key' => 'field_6760c04043451',
											'label' => 'Français',
											'name' => 'fr',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_6760c04643452',
											'label' => 'Anglais',
											'name' => 'en',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
									),
								),
								array(
									'key' => 'field_6760df5a42b95',
									'label' => 'autocomplete',
									'name' => 'autocomplete',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'email',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'password',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'tel',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'text',
											),
										),
									),
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 1,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6760b64c16c9f',
									'label' => 'accept',
									'name' => 'accept',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'file',
											),
										),
									),
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6760b99716ca7',
									'label' => 'step',
									'name' => 'step',
									'aria-label' => '',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'number',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'range',
											),
										),
									),
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => 0,
									'min' => 0,
									'max' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'step' => '0.1',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6760b40b379fd',
									'label' => 'multiple',
									'name' => 'multiple',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'email',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'file',
											),
										),
									),
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'ui' => 1,
								),
								array(
									'key' => 'field_6760b443379fe',
									'label' => 'readonly',
									'name' => 'readonly',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'email',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'month',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'number',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'password',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'tel',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'text',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'time',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'url',
											),
										),
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'week',
											),
										),
									),
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'ui' => 1,
								),
								array(
									'key' => 'field_6760be0045070',
									'label' => 'required',
									'name' => 'required',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '!=',
												'value' => 'radio',
											),
											array(
												'field' => 'field_67609942b7477',
												'operator' => '!=',
												'value' => 'checkbox',
											),
											array(
												'field' => 'field_67609942b7477',
												'operator' => '!=',
												'value' => 'range',
											),
											array(
												'field' => 'field_67609942b7477',
												'operator' => '!=',
												'value' => 'hidden',
											),
										),
									),
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'ui' => 1,
								),
								array(
									'key' => 'field_6760a8b14b62a',
									'label' => 'checkbox',
									'name' => 'checkbox',
									'aria-label' => '',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'checkbox',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'table',
									'min' => 0,
									'max' => 0,
									'collapsed' => '',
									'button_label' => 'Ajouter une checkbox',
									'rows_per_page' => 20,
									'sub_fields' => array(
										array(
											'key' => 'field_6760a9044b62b',
											'label' => 'Texte française',
											'name' => 'text_fr',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'parent_repeater' => 'field_6760a8b14b62a',
										),
										array(
											'key' => 'field_6760bfc24344f',
											'label' => 'Texte anglaise',
											'name' => 'text_en',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'parent_repeater' => 'field_6760a8b14b62a',
										),
										array(
											'key' => 'field_6760a90b4b62c',
											'label' => 'Valeur',
											'name' => 'value',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'parent_repeater' => 'field_6760a8b14b62a',
										),
										array(
											'key' => 'field_6760a9184b62d',
											'label' => 'checked',
											'name' => 'checked',
											'aria-label' => '',
											'type' => 'true_false',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'message' => '',
											'default_value' => 0,
											'allow_in_bindings' => 0,
											'ui_on_text' => '',
											'ui_off_text' => '',
											'ui' => 1,
											'parent_repeater' => 'field_6760a8b14b62a',
										),
									),
								),
								array(
									'key' => 'field_6760aab04b62e',
									'label' => 'radio',
									'name' => 'radio',
									'aria-label' => '',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'radio',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'table',
									'min' => 0,
									'max' => 0,
									'collapsed' => '',
									'button_label' => 'Ajouter un radio',
									'rows_per_page' => 20,
									'sub_fields' => array(
										array(
											'key' => 'field_6760aab04b62f',
											'label' => 'Texte français',
											'name' => 'text_fr',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'parent_repeater' => 'field_6760aab04b62e',
										),
										array(
											'key' => 'field_6760bfe743450',
											'label' => 'Texte anglais',
											'name' => 'text_en',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'parent_repeater' => 'field_6760aab04b62e',
										),
										array(
											'key' => 'field_6760aab04b630',
											'label' => 'Valeur',
											'name' => 'value',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'parent_repeater' => 'field_6760aab04b62e',
										),
										array(
											'key' => 'field_6760aab04b631',
											'label' => 'checked',
											'name' => 'checked',
											'aria-label' => '',
											'type' => 'true_false',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'message' => '',
											'default_value' => 0,
											'allow_in_bindings' => 0,
											'ui_on_text' => '',
											'ui_off_text' => '',
											'ui' => 1,
											'parent_repeater' => 'field_6760aab04b62e',
										),
									),
								),
								array(
									'key' => 'field_6762be9fd687d',
									'label' => 'Mask',
									'name' => 'mask',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'tel',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'ui' => 1,
								),
								array(
									'key' => 'field_6762ced13af83',
									'label' => 'Can be empty',
									'name' => 'can_be_empty',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_6760be0045070',
												'operator' => '!=',
												'value' => '1',
											),
											array(
												'field' => 'field_67609942b7477',
												'operator' => '!=',
												'value' => 'file',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'ui' => 1,
								),
								array(
									'key' => 'field_676416abb5143',
									'label' => 'Split',
									'name' => 'split',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'ui' => 1,
								),
								array(
									'key' => 'field_6762c044bb84f',
									'label' => 'minword',
									'name' => 'minword',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'text',
											),
										),
									),
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6762c063bb850',
									'label' => 'maxword',
									'name' => 'maxword',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_67609942b7477',
												'operator' => '==',
												'value' => 'text',
											),
										),
									),
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
							),
							'min' => '',
							'max' => '',
						),
						'layout_67609fadb7485' => array(
							'key' => 'layout_67609fadb7485',
							'name' => 'select',
							'label' => 'Select',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_67641c00c4841',
									'label' => 'Label',
									'name' => 'label',
									'aria-label' => '',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'table',
									'sub_fields' => array(
										array(
											'key' => 'field_67641c00c4842',
											'label' => 'Français',
											'name' => 'fr',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_67641c00c4843',
											'label' => 'Anglais',
											'name' => 'en',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_67642287443e7',
											'label' => 'Don\'t link',
											'name' => 'do_not_link',
											'aria-label' => '',
											'type' => 'true_false',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'message' => '',
											'default_value' => 0,
											'allow_in_bindings' => 0,
											'ui_on_text' => '',
											'ui_off_text' => '',
											'ui' => 1,
										),
									),
								),
								array(
									'key' => 'field_6760c1ebe235a',
									'label' => '',
									'name' => '',
									'aria-label' => '',
									'type' => 'message',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'new_lines' => '',
									'esc_html' => 0,
								),
								array(
									'key' => 'field_67609fadb7488',
									'label' => 'id',
									'name' => 'id',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_67609fadb7489',
									'label' => 'name',
									'name' => 'name',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_676112d00c2a0',
									'label' => 'placeholder',
									'name' => 'placeholder',
									'aria-label' => '',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'table',
									'sub_fields' => array(
										array(
											'key' => 'field_676112d00c2a1',
											'label' => 'Français',
											'name' => 'fr',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_676112d00c2a2',
											'label' => 'Anglais',
											'name' => 'en',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
									),
								),
								array(
									'key' => 'field_6760c44329396',
									'label' => 'required',
									'name' => 'required',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'ui' => 1,
								),
								array(
									'key' => 'field_6762cef43af84',
									'label' => 'Can be empty',
									'name' => 'can_be_empty',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_6760c44329396',
												'operator' => '!=',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'ui' => 1,
								),
								array(
									'key' => 'field_676416feb5144',
									'label' => 'Split',
									'name' => 'split',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'ui' => 1,
								),
								array(
									'key' => 'field_6761112da85ce',
									'label' => 'Liste',
									'name' => 'list',
									'aria-label' => '',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'table',
									'min' => 0,
									'max' => 0,
									'collapsed' => '',
									'button_label' => 'Ajouter un élément',
									'rows_per_page' => 20,
									'sub_fields' => array(
										array(
											'key' => 'field_67611145a85cf',
											'label' => 'Texte français',
											'name' => 'text_fr',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'parent_repeater' => 'field_6761112da85ce',
										),
										array(
											'key' => 'field_67611160a85d0',
											'label' => 'Texte anglais',
											'name' => 'text_en',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'parent_repeater' => 'field_6761112da85ce',
										),
										array(
											'key' => 'field_67611173a85d1',
											'label' => 'Valeur',
											'name' => 'value',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'parent_repeater' => 'field_6761112da85ce',
										),
									),
								),
							),
							'min' => '',
							'max' => '',
						),
						'layout_67609fc2b748c' => array(
							'key' => 'layout_67609fc2b748c',
							'name' => 'textarea',
							'label' => 'Textarea',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_67641c0dc4844',
									'label' => 'Label',
									'name' => 'label',
									'aria-label' => '',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'table',
									'sub_fields' => array(
										array(
											'key' => 'field_67641c0dc4845',
											'label' => 'Français',
											'name' => 'fr',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_67641c0dc4846',
											'label' => 'Anglais',
											'name' => 'en',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_6764229d443e8',
											'label' => 'Don\'t link',
											'name' => 'do_not_link',
											'aria-label' => '',
											'type' => 'true_false',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'message' => '',
											'default_value' => 0,
											'allow_in_bindings' => 0,
											'ui_on_text' => '',
											'ui_off_text' => '',
											'ui' => 1,
										),
									),
								),
								array(
									'key' => 'field_6760c20ee235c',
									'label' => '',
									'name' => '',
									'aria-label' => '',
									'type' => 'message',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'new_lines' => '',
									'esc_html' => 0,
								),
								array(
									'key' => 'field_67609fc2b748f',
									'label' => 'id',
									'name' => 'id',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_67609fc2b7490',
									'label' => 'name',
									'name' => 'name',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_676112f4c38a5',
									'label' => 'placeholder',
									'name' => 'placeholder',
									'aria-label' => '',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'table',
									'sub_fields' => array(
										array(
											'key' => 'field_676112f4c38a6',
											'label' => 'Français',
											'name' => 'fr',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_676112f4c38a7',
											'label' => 'Anglais',
											'name' => 'en',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'allow_in_bindings' => 0,
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
									),
								),
								array(
									'key' => 'field_6760c45329397',
									'label' => 'required',
									'name' => 'required',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'ui' => 1,
								),
								array(
									'key' => 'field_6760c4a5c9dbf',
									'label' => 'readonly',
									'name' => 'readonly',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'ui' => 1,
								),
								array(
									'key' => 'field_6762cf0a3af85',
									'label' => 'Can be empty',
									'name' => 'can_be_empty',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_6760c45329397',
												'operator' => '!=',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'ui' => 1,
								),
								array(
									'key' => 'field_6764170ab5145',
									'label' => 'Split',
									'name' => 'split',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'ui' => 1,
								),
								array(
									'key' => 'field_6762c5966ebf8',
									'label' => 'minlength',
									'name' => 'minlength',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6762c5996ebf9',
									'label' => 'maxlength',
									'name' => 'maxlength',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6762c082bb852',
									'label' => 'minword',
									'name' => 'minword',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6762c084bb853',
									'label' => 'maxword',
									'name' => 'maxword',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.3333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
							),
							'min' => '',
							'max' => '',
						),
					),
					'min' => '',
					'max' => '',
					'button_label' => 'Add Row',
				),
				array(
					'key' => 'field_6760c944c1d2b',
					'label' => 'Settings',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_6760c95dc1d2c',
					'label' => 'Slug',
					'name' => 'slug',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.3333333333',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6762c9ace2286',
					'label' => 'Bouton reset',
					'name' => 'reset_button',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.3333333333',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'allow_in_bindings' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'ui' => 1,
				),
				array(
					'key' => 'field_67643e0b2925c',
					'label' => 'Message de succès',
					'name' => 'success_message',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'sub_fields' => array(
						array(
							'key' => 'field_67643e382925d',
							'label' => 'Français',
							'name' => 'fr',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_67643e4a2925e',
							'label' => 'Anglais',
							'name' => 'en',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
					),
				),
				array(
					'key' => 'field_67643e552925f',
					'label' => 'Message d\'erreur',
					'name' => 'error_message',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'sub_fields' => array(
						array(
							'key' => 'field_67643e5529260',
							'label' => 'Français',
							'name' => 'fr',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_67643e5529261',
							'label' => 'Anglais',
							'name' => 'en',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
					),
				),
				array(
					'key' => 'field_67629a181871f',
					'label' => 'Email notifications',
					'name' => 'email_notifications',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => 'field_67629a6218720',
					'button_label' => 'Ajouter un envoi de courriel',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_67629a6218720',
							'label' => 'Sujet',
							'name' => 'subject',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_67643eac29262',
									'label' => 'Français',
									'name' => 'fr',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_67643eb229263',
									'label' => 'Anglais',
									'name' => 'en',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
							),
							'parent_repeater' => 'field_67629a181871f',
						),
						array(
							'key' => 'field_6762afc5bce9c',
							'label' => 'To',
							'name' => 'to',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'admin' => 'Admin',
								'user' => 'User',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'parent_repeater' => 'field_67629a181871f',
						),
						array(
							'key' => 'field_6762afc3bce9b',
							'label' => 'To email',
							'name' => 'to_email',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_6762afc5bce9c',
										'operator' => '==',
										'value' => 'admin',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_67629a181871f',
						),
						array(
							'key' => 'field_6762b00ebce9d',
							'label' => 'To field ID',
							'name' => 'to_field_id',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_6762afc5bce9c',
										'operator' => '==',
										'value' => 'user',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_67629a181871f',
						),
						array(
							'key' => 'field_67630afeb1d61',
							'label' => 'Sender',
							'name' => 'sender',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_67630b0fb1d62',
									'label' => 'Name',
									'name' => 'name',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_67630b15b1d63',
									'label' => 'Courriel',
									'name' => 'email',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
							),
							'parent_repeater' => 'field_67629a181871f',
						),
						array(
							'key' => 'field_67643ec429264',
							'label' => 'Message',
							'name' => 'message',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_67629c1218724',
									'label' => 'Français',
									'name' => 'fr',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'allow_in_bindings' => 0,
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
								),
								array(
									'key' => 'field_67643eda29265',
									'label' => 'Anglais',
									'name' => 'en',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'allow_in_bindings' => 0,
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
								),
							),
							'parent_repeater' => 'field_67629a181871f',
						),
						array(
							'key' => 'field_67629cbf18725',
							'label' => 'Attachments',
							'name' => 'attachments',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_6762afc5bce9c',
										'operator' => '==',
										'value' => 'user',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Ajouter un fichier',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_67629cd718726',
									'label' => 'Fichier',
									'name' => 'file',
									'aria-label' => '',
									'type' => 'file',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_size' => '',
									'max_size' => '',
									'mime_types' => '',
									'allow_in_bindings' => 0,
									'parent_repeater' => 'field_67629cbf18725',
								),
							),
							'parent_repeater' => 'field_67629a181871f',
						),
					),
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'form',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'acf_after_title',
			'style' => 'seamless',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
		) );

	}

	public function theme_settings_tab(){

		if(!current_user_can('edit_theme_options')) return;

		global $wp_admin_bar;


		$admin_url = admin_url();


		$args = array(
            'id' => 'is-forms',
            'title' => __('Forms', 'rwp-core'),
            'href' => $admin_url . 'edit.php?post_type=form',
            'parent' => 'is-site',
            'meta' => array(
                'class' => 'is-forms'
            )
        );
        $wp_admin_bar->add_node($args);

	}
    
}

new Render();